### ISSUE TITLE
Script does not execute when using 1.1 or later release

### ISSUE THREAD

**Issue by smjnab** [stephanvermeire/phaser-bitmapfont-generator#2]
Thanks for great tool! Got a problem running it since 1.1 release:

npm install -D @rtpa/phaser-bitmapfont-generator

and script file with default:
```
const generator = require('@rtpa/phaser-bitmapfont-generator');

(async ()=>{

    //generate textures
    await generator.TextStyle2BitmapFont();

    //exit node
    return process.exit(1);

})();
```

executed using terminal with: node scriptFile.js 

Makes it wait indefinitely to finish. No errors or warnings. Any version prior 1.1 works fine doing the above, last working version for me is 1.0.5.

**Comment by stephanvermeire** [comment]
That's weird. What node version and OS are you using?

Could you give the following sample a try:

```
const generator= require("../index");


(async ()=>{


    //generate textures
    await generator.TextStyle2BitmapFont({
        compression: null
    });

    //exit node
    return process.exit(1);


})();
```

**Comment by smjnab** [comment]
Fixed it! Error on my end.

I'm running two machines with Ubuntu based 18.04 (Lubuntu and KDE Neon) and on both I was certain I was using latest node 12, but turns out they were both running latest node 10 release because the source servers had not/did not want to change to 12 but did so silently. Thanks for asking for version as that made me notice this.

Using 12.16.3 LTS no problem, when using 10.20.1 it did not work.

**Comment by stephanvermeire** [comment]
Good to hear you resolved the issue! :-)
